name: Hi there example

on:
  push:

jobs:
# first job
  hi-there-example:
    runs-on: ubuntu-latest
    steps:
    - name: cowsay_Install
      run: pip install cowsay
    - name: cowsayRun
      run: cowsay -c cheese -t 'hey there'

  # 2nd job 
  cowpy-example:
    runs-on: ubuntu-latest
    steps:
    - name: cowpyExample
      run: pip install cowpy
    - name: cowpyRun
      run: cowpy -c tux hi there
  
  cowpy-2ndScript:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout
        - name: cowpyExample2
          run: pip install cowpy
        - name: run script2
          run: python bin/cowpy.py
     


