name: Hi there example

on:
  push:

jobs:

  cowpy-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - name: cowpyExample2
      run: pip install cowpy
    - name: run script2
      run: python bin/cowpy.py
     
